[package]
name = "maswali"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

[dev-dependencies]
rustfmt = "0.10"

[workspace.lints.clippy]
all = { level = "deny", priority = -100 }
restriction = { level = "deny", priority = -100 }
pedantic = { level = "deny", priority = -100 }
nursery = { level = "deny", priority = -100 }
cargo = { level = "deny", priority = -100 }
